GradientBoostingClassifier:
    n_estimators: 200  # ntrees
    max_depth: 5    # max_depth
    min_samples_split: 10   # min_rows
    learning_rate: 0.3   # learn_rate
    subsample: 0.8     # sample_rate
    max_features: 0.6  # col_sample_rate
    random_state: 5