artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Meet3456/HEART-INIT/raw/main/data.zip
  local_data_file: artifacts/data_ingestion/dataaa.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/heart.csv
  STATUS_FILE: artifacts/data_validation/status.txt